### PR TITLE
Pickup & Artifact Achievements, Texture Refactors

### PR DESCRIPTION
**Pull request by JaceDaDorito**

### CODE REVIEW

**Comment by JaceDaDorito** [comment]
This merge now includes the first pass of texture refactors across Base and Deprecated. Most of the duplicate textures should be cleared out. All common textures and meshes can now be found in Base/Common

**Comment by JaceDaDorito** [comment]
Btw whoever named a bunch of the old shit were fucked what is wrong with you

**Comment by gamrtiem** [comment]
"oh boy i cant wait to contribute to starstorm !!!!!"
kid named /deprecated/nemmando/:

**Comment by JaceDaDorito** [comment]
> "oh boy i cant wait to contribute to starstorm !!!!!" kid named /deprecated/:

What a fucking era of ror2 modding

**Comment by gamrtiem** [comment]
doing jods work ,.,,.,.

**Pull request merged**
