### PR TITLE
chirr is fukicng dead

### PR DESCRIPTION
**Pull request by nayDPz**
fixed nemmerc's weapons ignoring overlays

### CODE REVIEW

**Review by gamrtiem — COMMENTED** [review]
not cool ,,,,,. add unused chirr files back ,,.,.,,,,,.,,,

**Comment by gamrtiem** [comment]
i dont care add her back !!!!!

**Comment by swuff-star** [comment]
i need you. come here.

**Comment by gamrtiem** [comment]
were so jack .,,,,,.,.,,,,.,.,.,,

**Pull request merged**
