### PR TITLE
PT-BR Language

### PR DESCRIPTION
**Pull request by Kauzok**
Hello, I've translated missing files and fixed Portuguese language errors that had been left by the previous translator. I hope it meets the standards.

### CODE REVIEW

**Comment by Hevia** [comment]
PR looks good, ill go bother Nebby or Zen to merge this. Thanks for doing this!

**Comment by Kauzok** [comment]
Hello, I've finished reviewing once again and fixing all the noticed grammatical errors, with my last modified file being "SS2Lang_UnlocksBorg_pt.json."

I'd like to alert the reviewer that I don't know how to work with these "meta" files. Therefore, I didn't touch any of them. For the ones that were missing, I simply copied the same from the English version and changed "DefaultScriptImporter" to "TextScriptImporter." I leave it to the person who will merge my changes to fix any errors in those meta files. I hope you like my translation :)

**Comment by Hevia** [comment]
@Kauzok  You can always safely ignore meta files. Thanks for letting us know youre finished. We'll be merging this soon

**Review by Zenithrium — APPROVED** [review]
seems good!

**Pull request merged**
