### PR TITLE
content updae may 2023 year of the starstorm

### PR DESCRIPTION
**Pull request by swuff-star**
HEY DON'T MERGE THIS YET it's just a little bit away from being done but i'm pr'ing now to make a list of things that are done & for the sake of accessibility by everyone else:

**WHAT'S DONE:** 

 - Nemesis Commando: i think finalized. should be playtested a few times but i think is ready for release, fully. rewritten from ground up & deprecated old nemmando
 
 - Executioner: redone, i think almost ready for release. new m2 and special, big tweaks to fear. no alts and missing a grand mastery but am content shipping without just for sake of getting the character out given he's playable and fun

 - MULE: really early base kit that is certainly receiving changes. should be disabled for a thunderstore release.

 - Duplicator & Shock Drones: about done, but shock drone needs model still & need to set interactable spawning. character bodies are fully set up and shippable otherwise.

 - Ethereal Terminals: implemented, as well as ethereal teleporters, including a difficulty increase for each visited & new difficulties assigned after completion. should be disabled for a thunderstore release.

 - Items: added Insecticide, and reworked Pressurized Cannister

 - Events: redid storm vfx, added new rare "Fog" event on limited map pool.

### CODE REVIEW

**Comment by Nebby1999** [comment]
im going to merge itt anyways /jk

**Comment by Nebby1999** [comment]
> * Ethereal Terminals: implemented, as well as ethereal teleporters, including a difficulty increase for each visited & new difficulties assigned after completion. should be disabled for a thunderstore release.

Ok unironically the easiest way to do this is to just encapsulate the ethereal terminals in an ``#if DEBUG`` clause. because ss2 thundersotre releases will never be released on Debug mode
And if that somehow happens, the universe shall feel my wrath

**Comment by swuff-star** [comment]
imma just comment it out

**Comment by Zenithrium** [comment]
hard

**Comment by swuff-star** [comment]
shit oops didn't mean to push that last one

**Comment by Zenithrium** [comment]
ss2 leak!?!?!?!?!?!?!?!

**Comment by gamrtiem** [comment]
real ????

**Pull request merged**
