### PR TITLE
I HAVE NO IDEA WHAT IM DOING

### PR DESCRIPTION
**Pull request by leMalfaisant**
uhh is this thing on?? am i doing it correctly??
-gave exe a reticle and pod
-gave nemmando a reticle
-gave cyborg life but like one that doesnt work so hes broke lololo
-text fixes and additions:)
-i am so stupid

### CODE REVIEW

**Comment by swuff-star** [comment]
based

**Comment by Nebby1999** [comment]
Until Cyborg is in a ""Working"" stage (Working akin to chirr, so playable but not finished,) he shouldnt appear in the  survivor selection screen, i reckon you can just set his survivor def to hidden for now.

**Comment by Nebby1999** [comment]
So like... what did this do again?

**Comment by Nebby1999** [comment]
Swuff you're my friend but I'll politely ask you to not shitpost in pull requests, thanks.

**Comment by leMalfaisant** [comment]
Executioner
-Now comes out a pod and has a reticle
-Has no armor, lowered regen from 1.5 to 1.0 with levelup stats changed according

Nemesis Commando
-Now has a reticle and helmet emissions
-Increased regen from 1 to 2 with levelup stats changed
-Submission cooldown increased from 5 to 7, Dodge cooldown decreased from 5 to 4

Items
-Re-enabled Relic of Force
-Disabled Dungus, Erratic Gadget, and Coffee Bag until I can find new ideas for them
-Made Needle require less pricks but didnt change the pickup text lolololo
*------- might be forgetting 1-2 things -------*
also hi swuff youre in time to see me admit i fixed not even a single bug and just goofed off changing numbers ill do it now i prommy

**Comment by leMalfaisant** [comment]
since last time on dragonball z:
-added unlock icons
-lowered the time event text is onscreen
-did some absolutely stupid shit and instantly reverted it
-make exe's pistol fire like slightly faster i think idk

**Comment by leMalfaisant** [comment]
Fixes #21 and fixes #28 btw

**Comment by Zenithrium** [comment]
i think you reverted the fire rate in a5fd916

**Comment by leMalfaisant** [comment]
i thought i changed it back but github is my worst enemy

**Comment by Nebby1999** [comment]
No puedo hacer merge commit por conflictos en la branch, veré qué hacer mañana en la mañana

**Comment by Nebby1999** [comment]
there are still merge conflicts 😭

**Pull request closed without merging**
