### PR TITLE
0.3.41 Changes 

### PR DESCRIPTION
**Pull request by Zenithrium**
not quite there but it does work functionally and has a model i made, just unfinished visuals both for a marked enemy and a buffed enemy. code could also use polishing / cleaning

### CODE REVIEW

**Comment by leMalfaisant** [comment]
PR 100 :P

**Comment by Zenithrium** [comment]
And it's termination! Perfect time to quit :)

**Comment by leMalfaisant** [comment]
So true….

**Comment by Zenithrium** [comment]
completely renaming this PR because i ended up doing a lot of changes here - not quite merge ready because i want to fix one or 2 more things but it's close

**Comment by Zenithrium** [comment]
0.3.41 changelog (at least so far)
    - Adds Relic of Termination, with temp VFX.
    - RiskyMod compatability for Droid Head.
    - Droid Head will no longer spawn void infestors. (#91)
    - Fixed VFX for Relic of Force.
    - Nkota's Heritage can no longer drop itself.
    - Losing Baby's Toys no longer reduces your level - it now adds the levels gained from it back to your current level. This-readding does not proc Nkota's Heritage. (#109)
    - On skills with multiple base stocks, X4 will only proc once (+1 per additional stock (ex backup mag)) per recharge interval. This primarily normalizes the healing gained form skills like Nemmando's Single Tap and Mul-T's Power Mode. (#98, #102)
    - X4 heals on firing a sniper shot on Railgunner, like backup mag, rather than healing you on scoping in for their default secondary. No change to the alt secondary. (#102)
    - Added all DLC0 item displays for Executioner.
    - Bottled Chaos can no longer activate Back Thruster, MIDAS, and Pressurized Canister.
    - Executioner should no longer rarely become a lantern. (this is kind of a hacky fix - hopefully it worked) (#94, #96)
    - Portable Reactor can appear on enemies again (with fourthed duration) because it's hilarious. Also reduces turret / ally invulnerability duration to one fourth. (#111)
    - Fixed up the logbook. Items are now positioned better and have cleaner descriptions. (#108)

**Pull request merged**
